# Generated by Django 4.2.7 on 2025-10-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('sales', 'Ventas'), ('inventory', 'Inventario'), ('customers', 'Clientes'), ('financial', 'Financiero')], max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
